// src/utils/disposableEmailDomains.js

const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com", "guerrillamail.com", "guerrillamail.info",
  "guerrillamail.biz", "guerrillamail.de", "guerrillamail.net",
  "guerrillamail.org", "grr.la", "sharklasers.com", "guerrillamailblock.com",
  "spam4.me", "yopmail.com", "yopmail.fr", "cool.fr.nf", "jetable.fr.nf",
  "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr",
  "yep.it", "jetable.pp.ua", "trashmail.me", "trashmail.at",
  "trashmail.io", "trashmail.com", "trashmail.net", "trashmail.org",
  "trashmailer.com", "trash-mail.at", "dispostable.com",
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempr.email",
  "tempinbox.com", "fakeinbox.com", "fakeinbox.net",
  "mailnull.com", "maildrop.cc", "mailnesia.com",
  "mailforspam.com", "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "throwam.com", "throwam.net", "throwaway.email",
  "discard.email", "discardmail.com", "discardmail.de",
  "getairmail.com", "filzmail.com",
  "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "10minutemail.de", "10minemail.com", "10mail.org",
  "20minutemail.com", "20minutemail.it",
  "mailexpire.com", "spamex.com",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "einrot.com", "einrot.de", "emkei.cz",
  "crazymailing.com", "spamfree24.org", "spamfree24.de",
  "spamfree24.eu", "spamfree24.info", "spamfree24.net",
  "binkmail.com", "boximail.com", "clrmail.com", "rcpt.at",
  "trbvm.com", "klzlk.com", "zetmail.com", "whyspam.me",
  "mt2009.com", "mt2014.com", "bspamfree.org", "haltospam.com",
  "jetable.com", "jetable.net", "jetable.org",
  "nada.email", "nada.ltd", "spamgap.com", "mailscrap.com",
  "owlpic.com", "drdrb.net", "drdrb.com", "objectmail.com",
  "kekmail.com", "spambox.us", "supermailer.jp",
  "byom.de", "centermail.com", "centermail.net",
  "chogmail.com", "choicemail1.com", "cool.fr.nf",
  "deadaddress.com", "despam.it", "devnullmail.com",
  "dingbone.com", "dispostable.com", "dodgeit.com",
  "dodgit.com", "donemail.ru", "dontreg.com",
  "dump-email.info", "dumpandfuck.com", "dumpmail.de",
  "dumpyemail.com", "e4ward.com", "email60.com",
  "emailias.com", "emailigo.com", "emailinfive.com",
  "emailisvalid.com", "emailmiser.com", "emailsensei.com",
  "emailtemporanea.com", "emailtemporanea.net", "emailtemporanea.org",
  "emailthe.net", "emailtmp.com", "emailwarden.com",
  "enterto.com", "ephemail.net", "explodemail.com",
  "fastacura.com", "fastchevy.com", "fastchrysler.com",
  "fastkawasaki.com", "fastmazda.com", "fastmitsubishi.com",
  "fastnissan.com", "fastsubaru.com", "fastsuzuki.com",
  "fasttoyota.com", "fastyamaha.com", "fivemail.de",
  "fleckens.hu", "frapmail.com", "front14.org",
  "fudgerub.com", "garliclife.com", "gelitik.in",
  "givmail.com", "gowikibooks.com", "gowikicampus.com",
  "gowikicars.com", "gowikifilms.com", "gowikigames.com",
  "gowikimusic.com", "gowikinetwork.com", "gowikitravel.com",
  "gowikitv.com", "great-host.in", "greensloth.com",
  "gsrv.co.uk", "gustr.com", "haltospam.com",
  "harakirimail.com", "hat-geld.de", "herp.in",
  "hidemail.de", "hidzz.com", "hmamail.com",
  "hopemail.biz", "ieatspam.eu", "ieatspam.info",
  "ieh-mail.de", "ihateyoualot.info", "iheartspam.org",
  "imails.info", "inbax.tk", "inbox.si",
  "inboxalias.com", "inboxclean.com", "inboxclean.org",
  "inoutmail.de", "inoutmail.eu", "inoutmail.info",
  "inoutmail.net", "insorg-mail.info", "ipoo.org",
  "irish2me.com", "iwi.net", "jetable.fr.nf",
  "jnxjn.com", "jourrapide.com", "jsrsolutions.com",
  "kasmail.com", "kaspop.com", "keepmymail.com",
  "killmail.com", "killmail.net", "klassmaster.com",
  "klzlk.com", "koszmail.pl", "kurzepost.de",
  "letthemeatspam.com", "lhsdv.com", "ligsb.com",
  "litedrop.com", "lol.ovpn.to", "lolfreak.net",
  "lookugly.com", "lopl.co.cc", "lortemail.dk",
  "losemymail.com", "lroid.com", "m21.cc",
  "mail-filter.com", "mail-temporaire.fr", "mail.by",
  "mail2rss.org", "mail333.com", "mailbidon.com",
  "mailbiz.biz", "mailblocks.com", "mailbucket.org",
  "mailc.net", "mailcan.com", "mailcat.biz",
  "mailcatch.com", "mailde.de", "mailde.info",
  "maildrop.cc", "maileimer.de", "mailexpire.com",
  "mailf5.com", "mailfall.com", "mailfree.ga",
  "mailfreeonline.com", "mailguard.me", "mailhazard.com",
  "mailhazard.us", "mailimate.com", "mailin8r.com",
  "mailinatar.com", "mailinater.com", "mailinator.net",
  "mailinator.org", "mailinator.us", "mailinator2.com",
  "mailincubator.com", "mailismagic.com", "mailjunk.eu",
  "mailme.lv", "mailme24.com", "mailmetrash.com",
  "mailmoat.com", "mailnew.com", "mailnull.com",
  "mailpick.biz", "mailproxsy.com", "mailquack.com",
  "mailrock.biz", "mailsac.com", "mailscrap.com",
  "mailshell.com", "mailsiphon.com", "mailslite.com",
  "mailsnull.com", "mailspam.me", "mailspam.xyz",
  "mailspot.net", "mailsquirt.io", "mailtemp.info",
  "mailtome.de", "mailtothis.com", "mailtrash.net",
  "mailtv.net", "mailtv.tv", "mailzilla.com",
  "makemetheking.com", "manybrain.com", "mbx.cc",
  "meltmail.com", "messagebeamer.de", "mezimages.net",
  "ministry-of-silly-walks.de", "mintemail.com", "misterpinball.de",
  "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
  "monumentmail.com", "msa.minemail.com", "mt2014.com",
  "mt2015.com", "mx0.wwwnew.eu", "my10minutemail.com",
  "myalias.pw", "myblue.life", "mycleaninbox.net",
  "mymail-in.net", "mymailoasis.com", "mynetstore.de",
  "mypacks.net", "mypartyclip.de", "myphantomemail.com",
  "mysamp.de", "myspaceinc.com", "myspaceinc.net",
  "myspaceinc.org", "myspacepimped.com", "mytemp.email",
  "mytrashmail.com", "neomailbox.com", "nepwk.com",
  "nervmich.net", "nervtmich.net", "netmails.com",
  "netmails.net", "netzidiot.de", "nevermail.de",
  "newbpotato.tk", "nice-4u.com", "nincsmail.hu",
  "nnh.com", "no-spam.ws", "noblepioneer.com",
  "noclickemail.com", "nogmailspam.info", "nomail.pw",
  "nomail.xl.cx", "nomail2me.com", "nomorespamemails.com",
  "nonspam.eu", "nonspammer.de", "noref.in",
  "norseforce.com", "notmailinator.com", "nowmymail.com",
  "nwldx.com", "objectmail.com", "obobbo.com",
  "odnorazovoe.ru", "one-time.email", "oneoffemail.com",
  "onewaymail.com", "online.ms", "opayq.com",
  "ordinaryamerican.net", "otherinbox.comsafe-mail.net",
  "ourklips.com", "outlawspam.com", "ovpn.to",
  "owlpic.com", "pancakemail.com", "paplease.com",
  "pcusers.otherinbox.com", "pepbot.com", "phreaker.net",
  "pimpedupmyspace.com", "pjjkp.com", "plexolan.de",
  "poczta.onet.pl", "politikerclub.de", "poofy.org",
  "pookmail.com", "privacy.net", "privatdemail.net",
  "proxymail.eu", "prtnx.com", "punkass.com",
  "putthisinyourspamdatabase.com", "putthisinyourspamdatabase.net",
  "qq.com", "quickinbox.com", "rcpt.at",
  "reallymymail.com", "reconmail.com", "recyclemail.dk",
  "regbypass.com", "regbypass.comsafe-mail.net",
  "rejectmail.com", "rklips.com", "rmqkr.net",
  "rppkn.com", "rtrtr.com", "s0ny.net",
  "safe-mail.net", "safetymail.info", "safetypost.de",
  "sandelf.de", "saynotospams.com", "schafmail.de",
  "schrott-email.de", "secretemail.de", "secure-mail.biz",
  "sendspamhere.com", "sharklasers.com", "shieldedmail.com",
  "shiftmail.com", "shitmail.me", "shitware.nl",
  "shmeriously.com", "shortmail.net", "sibmail.com",
  "skeefmail.com", "slaskpost.se", "slopsbox.com",
  "smellfear.com", "smellrear.com", "sneakemail.com",
  "sneakmail.de", "snkmail.com", "sofimail.com",
  "sofort-mail.de", "sogetthis.com", "soodonims.com",
  "spam.la", "spam.mn", "spam.su",
  "spam4.me", "spamavert.com", "spambob.com",
  "spambob.net", "spambob.org", "spambog.com",
  "spambog.de", "spambog.ru", "spambox.info",
  "spambox.irishspringrealty.com", "spambox.us", "spamcannon.com",
  "spamcannon.net", "spamcero.com", "spamcon.org",
  "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net",
  "spamcowboy.org", "spamday.com", "spamex.com",
  "spamfree.eu", "spamfree24.de", "spamfree24.eu",
  "spamfree24.info", "spamfree24.net", "spamfree24.org",
  "spamgoes.in", "spamgourmet.com", "spamgourmet.net",
  "spamgourmet.org", "spamherelots.com", "spamhereplease.com",
  "spamhole.com", "spamify.com", "spaminator.de",
  "spamkill.info", "spaml.com", "spaml.de",
  "spammotel.com", "spamobox.com", "spamoff.de",
  "spamslicer.com", "spamspot.com", "spamthis.co.uk",
  "spamthisplease.com", "spamtrail.com", "spamtroll.net",
  "speed.1s.fr", "spoofmail.de", "stuffmail.de",
  "super-mailer.jp", "supergreatmail.com", "supermailer.jp",
  "suremail.info", "sweetxxx.de", "tafmail.com",
  "tagyourself.com", "teewars.org", "teleworm.com",
  "teleworm.us", "temp-mail.de", "temp-mail.io",
  "temp-mail.org", "temp-mail.ru", "temp.emeraldwebmail.com",
  "temp.headstrong.de", "tempail.com", "tempalias.com",
  "tempe-mail.com", "tempemail.biz", "tempemail.co.za",
  "tempemail.com", "tempemail.net", "tempinbox.co.uk",
  "tempinbox.com", "tempmail.eu", "tempmail.it",
  "tempmail2.com", "tempmaildemo.com", "tempmailer.com",
  "tempmailer.de", "tempomail.fr", "temporarioemail.com.br",
  "temporaryemail.net", "temporaryemail.us", "temporaryforwarding.com",
  "temporaryinbox.com", "temporarymailaddress.com", "tempthe.net",
  "thanksnospam.info", "thecloudindex.com", "thisisnotmyrealemail.com",
  "throam.com", "throwam.com", "throwaway.email",
  "throwam.net", "tilien.com", "tittbit.in",
  "tizi.com", "tmailinator.com", "toiea.com",
  "tradermail.info", "trash-amil.com", "trash-mail.at",
  "trash-mail.com", "trash-mail.de", "trash-mail.ga",
  "trash-mail.io", "trash-mail.tk", "trash2009.com",
  "trash2010.com", "trash2011.com", "trashdevil.com",
  "trashdevil.de", "trashemail.de", "trashimail.com",
  "trashmail.at", "trashmail.com", "trashmail.io",
  "trashmail.me", "trashmail.net", "trashmail.org",
  "trashmail.xyz", "trashmailer.com", "trashmalware.com",
  "trbvm.com", "trialmail.de", "trickmail.net",
  "trillianpro.com", "tryalert.com", "turual.com",
  "twinmail.de", "tyldd.com", "uggsrock.com",
  "umail.net", "upliftnow.com", "uplipht.com",
  "uroid.com", "us.af", "venompen.com",
  "veryrealemail.com", "vidchart.com", "viditag.com",
  "viewcastmedia.com", "viewcastmedia.net", "viewcastmedia.org",
  "viralplays.com", "vomoto.com", "vpn.st",
  "vsimcard.com", "vubby.com", "walala.org",
  "walkmail.net", "walkmail.ru", "webemail.me",
  "weg-werf-email.de", "wegwerf-email.at", "wegwerf-email.de",
  "wegwerf-email.net", "wegwerf-email.org", "wegwerfadresse.de",
  "wegwerfemail.com", "wegwerfemail.de", "wegwerfemail.info",
  "wegwerfemail.net", "wegwerfemail.org", "wegwerfmail.de",
  "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org",
  "wh4f.org", "whopy.com", "whyspam.me",
  "wickmail.net", "wilemail.com", "willhackforfood.biz",
  "willselfdestruct.com", "winemaven.info", "wronghead.com",
  "wuzupmail.net", "www.e4ward.com", "www.mailinator.com",
  "wwwnew.eu", "xagloo.co", "xagloo.com",
  "xemaps.com", "xents.com", "xmaily.com",
  "xoxy.net", "xyzfree.net", "yapped.net",
  "yeah.net", "yepmail.net", "yert.ye.vc",
  "yomail.info", "yopmail.com", "yopmail.fr",
  "yopmail.gq", "yourdomain.com", "yuurok.com",
  "z1p.biz", "za.com", "zebins.com",
  "zebins.eu", "zehnminuten.de", "zehnminutenmail.de",
  "zetmail.com", "zippymail.info", "zoaxe.com",
  "zoemail.net", "zoemail.org", "zomg.info",
  "zxcv.com", "zxcvbnm.com", "zzz.com",
]);

/**
 * Returns true if the email uses a known disposable domain.
 * @param {string} email
 * @returns {boolean}
 */
export function isDisposableEmail(email) {
  if (!email || !email.includes("@")) return false;
  const domain = email.split("@")[1].toLowerCase().trim();
  return DISPOSABLE_DOMAINS.has(domain);
}
